#include <iostream>
#define SET_SIZE_MAX 100

//					PART A

// ------------  INSTRUCTIONS ---------------
//			DO NOT MODIFY THIS FILE. 
// Failure to heed this warning will likely result in a failing grade 
// on this assignment!
// For the implementation of the following you are NOT permitted to 
// use math.h / <cmath> or ANY other library includes other than the 
// already provided <iostream>

// ---------- TSet FUNCTIONALITY ------------
// The following is required functionality of the set theory portion 
// of the project. You are NOT required to re-implement or modify ANY 
// parts of this header file. This includes the TSet in its entirety.
// This is the implementation for a Set of integers between 1 and 100 inclusive
// where integer values of '0' in the array are considered 'empty' ie. not an element. 
// U = { x : x E Z, x >= 1 & x <= 100 }
struct TSet
{
private:
	int* m_piArray = nullptr;
	const int m_iMaxSize = SET_SIZE_MAX;

public:
	TSet()
	{
		m_piArray = new int[SET_SIZE_MAX];
		SetClear();
	}

	~TSet()
	{
		delete[] m_piArray;
	}

	void Print()
	{
		std::cout << "\nSet Elements: {";
		for (int i = 0; i < m_iMaxSize; i++)
		{
			if (m_piArray[i] != 0)
			{
				std::cout << " " << m_piArray[i];
				if (i < m_iMaxSize - 1)
				{
					std::cout << ",";
				}
			}
		}
		std::cout << " }; ";
	}

	void SetClear()
	{
		for (int n = 0; n < m_iMaxSize; n++)
		{
			m_piArray[n] = 0;
		}
	}

	void SetUniversal()
	{
		for (int n = 0; n < m_iMaxSize; n++)
		{
			m_piArray[n] = n + 1;
		}
	}

	void AddElement(int _iElement)
	{
		if ((_iElement <= m_iMaxSize) && (_iElement > 0))
		{
			m_piArray[_iElement - 1] = _iElement;
		}
	}

	void RemoveElement(int _iElement)
	{
		if ((_iElement <= m_iMaxSize) && (_iElement > 0))
		{
			m_piArray[_iElement - 1] = 0;
		}
	}

	bool ContainsElement(int _iElement)
	{
		if ((_iElement <= m_iMaxSize) && (_iElement > 0))
		{
			return (m_piArray[_iElement - 1] != 0);
		}
		return false;
	}
};

// ----------- LIBRARY FUNCTION DECLARITONS ---------------
// You are to implement the following functions in the appropriately
// generated discretemaths.cpp implementation/definition file.
// The above "discretemaths.cpp" file is specifically to be
// created/generated by you in the course of completing this project.
// 

// Scalar "size" (i.e. without sign)
float Magnitude(const float _kfX);

// The "sign/direction" of our value (i.e. is it positive or is it negative)
float Signum(const float _kfX);

/// <summary>
/// Returns the nearest integer that is lower or equal to
/// </summary>
/// <param name="_kfX">the value to the floor</param>
/// <returns>return the floored value</returns>
float Floor(const float _kfX);

/// <summary>
/// Returns the nearest integer that is greater or equal to
/// </summary>
/// <param name="_kfX">the value to the floor</param>
/// <returns>return the floored value</returns>
float Ceiling(const float _kfX);

// ! Returns n * n-1 * n-2 * n-3 * n-4 * n-5 ... to * 1
// Important to remember our 0!
unsigned long long Factorial(const unsigned int _kdn);

// Probability part 1
// Repition is not allowed
// (n!) / (r! (n - r)!)
unsigned long long Combination(const unsigned int _kuin, const unsigned int _kuir);

// Probability part 2
// Repition is not allowed
// (n!) / ((n - r)!)
unsigned long long Permutation(const unsigned int _kuin, const unsigned int _kuir);

// Number of elements in the set
int Cardinality(TSet& _rSet);

// The number of all possible subsets
unsigned long long Power(TSet& _rSet);

// Returns the total number of unique ordered pairs
unsigned long long CartesianProduct(TSet& _rA, TSet& _rB);

// All bools returns True : False (For context)

// Checks if both TSets have the same elements
bool Equals(TSet& _rA, TSet& _rB);

// Checks if _rA is a subset of _rB 
bool Subset(TSet& _rA, TSet& _rB);

// Checks if _rA is a Superset of _rB
bool Superset(TSet& _rA, TSet& _rB);

// Checks if two sets are mutually exclusive (i.e they share no common elements)
bool Disjoint(TSet& _rA, TSet& _rB);

// Combines the elements from _rA & rB and gives a thrid result
TSet& Union(TSet& _rA, TSet& _rB, TSet& _rResultant);

// Finds the intersection of the two TSets
TSet& Intersection(TSet& _rA, TSet& _rB, TSet& _rResultant);

// I think this one gives the result of only elemets in TSet _rA & not _rB (not sure)
TSet& SetDifference(TSet& _rA, TSet& _rB, TSet& _rResultant);

// returns all elements that exist in both sets
TSet& SymmetricDifference(TSet& _rA, TSet& _rB, TSet& _rResultant);

// Calculates the relative complement
TSet& Compliment(TSet& _rA, TSet& _rResultant);
