#include <iostream>

// ----------- LIBRARY FUNCTION DECLARITONS ---------------
// You are to implement the following functions in the appropriately
// generated discretemaths.cpp implementation/definition file.
// The above "discretemaths.cpp" file is specifically to be
// created/generated by you in the course of completing this project.
// 

float Magnitude(const float _kfX);

float Signum(const float _kfX);

float Floor(const float _kfX);

float Ceiling(const float _kfX);

unsigned long long Factorial(const unsigned int _kdn);

unsigned long long Combination(const unsigned int _kuin, const unsigned int _kuir);

unsigned long long Permutation(const unsigned int _kuin, const unsigned int _kuir);

int Cardinality(TSet& _rSet);

unsigned long long Power(TSet& _rSet);

unsigned long long CartesianProduct(TSet& _rA, TSet& _rB);

bool Equals(TSet& _rA, TSet& _rB);

bool Subset(TSet& _rA, TSet& _rB);

bool Superset(TSet& _rA, TSet& _rB);

bool Disjoint(TSet& _rA, TSet& _rB);

TSet& Union(TSet& _rA, TSet& _rB, TSet& _rResultant);

TSet& Intersection(TSet& _rA, TSet& _rB, TSet& _rResultant);

TSet& SetDifference(TSet& _rA, TSet& _rB, TSet& _rResultant);

TSet& SymmetricDifference(TSet& _rA, TSet& _rB, TSet& _rResultant);

TSet& Compliment(TSet& _rA, TSet& _rResultant);
